versions:
  # "0.18.8.rc1-20240905-git-vili":
  #   folder: "0.18.8.rc1"
  # "0.18.8.rc1-git-6f85c88-odr":
  #   folder: "0.18.8.rc1"
  # "0.18.8.rc1-odr-git-3dcf842":
  #   folder: "0.18.8.rc1"
  "0.18.8.rc1-odr-git-eb5d291":
    folder: "0.18.8.rc1"
