name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  renovate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
