name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  renovate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 20

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
